# Default resources fro snakemake
---
__use_yte__: true

default-resources:
    runtime: 1h
    mem_mb: 1024


set-threads:
  fastp__: 8
  bowtie2__build__: 24
  bowtie2__map__: 24
  bowtie2__unaligned__: 24
  bowtie2__clean__: 24

set-resources:
  fastp__:
    mem_mb: 8G
    runtime: 30m
  bowtie2__build__:
    mem_mb: 32 * 1024 * 2 ** (attempt - 1)
    runtime: 12h
  bowtie2__map__:
    mem_mb: 32 * 1024 * 2 ** (attempt - 1)
    runtime: 12h
  bowtie2__unaligned__:
    mem_mb: 8G
    runtime: 1h
  nonpareil__:
    mem_mb: 4G
    runtime: 6h