# Default resources for snakemake
---
__use_yte__: true

default-resources:
    runtime: 1h
    mem_mb: 1024


set-threads:
  # preprocess
  preprocess__fastp: 8
  preprocess__bowtie2__build: 24
  preprocess__bowtie2__map: 24
  preprocess__bowtie2__fastq: 24
  preprocess__bowtie2__clean: 24
  preprocess__kraken2__assign: 8


set-resources:
  # preprocess
  preprocess__fastp:
    mem_mb: 8G
    runtime: 30m
  preprocess__bowtie2__build:
    mem_mb: 32 * 1024 * 2 ** (attempt - 1)
    runtime: 12h
  preprocess__bowtie2__map:
    mem_mb: 32 * 1024 * 2 ** (attempt - 1)
    runtime: 12h
  preprocess__bowtie2__fastq:
    mem_mb: 8G
    runtime: 1h
  preprocess__nonpareil__run:
    mem_mb: 4G
    runtime: 6h
