hosts:  # Reads will be mapped sequentially
  human: resources/reference/human_22_sub.fa.gz
  chicken: resources/reference/chicken_39_sub.fa.gz
  # GRCg7b: resources/references/REF0003-GRCg7b/GCF_016699485.2_bGalGal1.mat.broiler.GRCg7b_genomic.fna.gz
  # GRCh38: resources/references/REF0001-GRC38/GCF_000001405.40_GRCh38.p14_genomic.fna.gz
  # Sscrofa11.1: resources/references/REF0002-Sscrofa11.1/GCF_000003025.6_Sscrofa11.1_genomic.fna.gz


databases:
  kraken2:
    mock1: resources/databases/kraken2/kraken2_RefSeqV205_Complete_500GB
    # mock2: resources/kraken2_mock  # another db
    # refseq500: resources/databases/kraken2/kraken2_RefSeqV205_Complete_500GB/20220505/
  singlem: resources/databases/singlem/S4.3.0.GTDB_r220.metapackage_20240523.smpkg.zb
