preprocess:
  fastp:
    extra: " --length_required 75 --trim_poly_g --trim_poly_x"
  bowtie2:
    bowtie2_extra: ""
    samtools_extra: "-m 1G"
  kraken2:
    bracken:
      extra: "-r 150 -t 0 -l S"
